### ISSUE TITLE
hamburger & tittle on same line

### ISSUE THREAD

**Issue by JosephMcArthur** [sparcopen/declaring-independence#26]
The fact these are not aligned on desktop drives me nuts, if easy, would be good to fix

![image](https://user-images.githubusercontent.com/4953703/40303271-09192500-5cea-11e8-803b-9a770ea9c95d.png)

**Comment by markmacgillivray** [comment]
Changed _sass/layout/_header.scss to have a #header include breakpoint at xlarge of padding-top:2em instead of 6.5em

**Comment by JosephMcArthur** [comment]
Thanks!
