### ISSUE TITLE
make bullet points same size as normal text

### ISSUE THREAD

**Issue by JosephMcArthur** [sparcopen/declaring-independence#28]
e.g https://declaring-independence.org/why-open-access-and-why-now

**Comment by markmacgillivray** [comment]
Updated _sass/components/_list.scss to use font-size:1.3em for ol li and ul li, to match the change someone already made in _sass/base/typography.scss changing the font-size of p tags to 1.3em.

**Comment by JosephMcArthur** [comment]
Ah, I think the headerbar (which uses li for each item) has been affected by this and now doesn't look great. Would be better restored to it's previous size.

**Comment by markmacgillivray** [comment]
Do you mean the left hand menu bar? Not sure there is really a header bar on this site.

Will add an overwrite for li elements on the left hand menu and see how that comes out.

**Comment by markmacgillivray** [comment]
Changed the left nav menu back to smaller list font size, is that OK?

**Comment by JosephMcArthur** [comment]
Perfect, closing.
