### ISSUE TITLE
shrink images used to make pages load faster (using lossless compression)

### ISSUE THREAD

**Issue by JosephMcArthur** [sparcopen/declaring-independence#32]

**Comment by markmacgillivray** [comment]
Shrunk assets/HughThomas_cropped.jpg to 73K from about 350K

alco_logo.png is already small at 9K

ALCO.jpg does not appear to be used on the site
Neither is cool_academic.png
Nor hughandalcoArtboard.png

Shrunk hughandalcoforbannerArtboard.png from 2.2MB to 439K then made a jpg version at 100K, and changed the ref to the image in the letter-from-an-editor file.

Scaled HughThomas.JPG down to 84K from a few hundred - BUT this image does not actually get used on the site, although it is included as an og:image tag on the letter-from-an-editor.md page, resulting in an extra file download for that page even though the image is not used. Also, as it happens, the link on that page to the file is wrong, so it 404s anyway. I would recommend linking to an image that IS used on the page, that way not needing an unnecessary download, or not even bothering with this image tag at all.

independent_academic.png does not get used on the site, did not change it

Shrunk tiny_sparc.png from 9K to 4K

**Comment by JosephMcArthur** [comment]
fab, thank you!

**Comment by JosephMcArthur** [comment]
@markmacgillivray the homepage image is a bit too pixelated I think. Could we use a larger file with higher quality please?

**Comment by markmacgillivray** [comment]
OK, the image is now has 50% larger filesize than the last shrink attempt, but still quarter of what it was before we did the shrinking. It is still at 500px wide, which is enough for the size it is displaying at.
